apiVersion: v1
kind: Namespace
metadata:
  name: shopee
  labels:
    name: shopee
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tiki-dev
  labels:
    name: tiki-dev
    environment: development
    istio-injection: enabled
