apiVersion: v1
kind: Namespace
metadata:
  name: tiki
  labels:
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: tiki-infra
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tiki-observability
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tiki-gitops
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tiki-ingress
  labels:
    istio-injection: disabled
