apiVersion: v1
kind: ResourceQuota
metadata:
  name: tiki-quota
  namespace: tiki
spec:
  hard:
    requests.cpu: "40"
    requests.memory: 80Gi
    limits.cpu: "80"
    limits.memory: 160Gi
    persistentvolumeclaims: "50"
    pods: "100"
    services: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tiki-limits
  namespace: tiki
spec:
  limits:
    - default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
        cpu: 200m
        memory: 256Mi
      type: Container
