-- Auto-create all databases if they don't exist
-- This runs on MySQL first startup via /docker-entrypoint-initdb.d/

CREATE DATABASE IF NOT EXISTS tiki_platform;
CREATE DATABASE IF NOT EXISTS tiki_auth;
CREATE DATABASE IF NOT EXISTS tiki_cart;
CREATE DATABASE IF NOT EXISTS tiki_checkout;
CREATE DATABASE IF NOT EXISTS tiki_inventory;
CREATE DATABASE IF NOT EXISTS tiki_order;
CREATE DATABASE IF NOT EXISTS tiki_payment;
CREATE DATABASE IF NOT EXISTS tiki_product;
CREATE DATABASE IF NOT EXISTS tiki_promotion;
CREATE DATABASE IF NOT EXISTS tiki_shipment;
CREATE DATABASE IF NOT EXISTS tiki_catalog;
CREATE DATABASE IF NOT EXISTS tiki_oms;
CREATE DATABASE IF NOT EXISTS tiki_logistics;
CREATE DATABASE IF NOT EXISTS tiki_notification;
CREATE DATABASE IF NOT EXISTS tiki_search;
CREATE DATABASE IF NOT EXISTS tiki_recommendation;
CREATE DATABASE IF NOT EXISTS tiki_analytics;
CREATE DATABASE IF NOT EXISTS tiki_fraud;
CREATE DATABASE IF NOT EXISTS tiki_billing;
CREATE DATABASE IF NOT EXISTS tiki_advertising;
CREATE DATABASE IF NOT EXISTS tiki_live_commerce;
CREATE DATABASE IF NOT EXISTS tiki_user_behavior;
CREATE DATABASE IF NOT EXISTS tiki_developer;
CREATE DATABASE IF NOT EXISTS tiki_sre;
CREATE DATABASE IF NOT EXISTS tiki_service_mesh;
CREATE DATABASE IF NOT EXISTS tiki_global_infra;
CREATE DATABASE IF NOT EXISTS tiki_rec_vector;
CREATE DATABASE IF NOT EXISTS tiki_payment_ledger;
CREATE DATABASE IF NOT EXISTS tiki_oms_fulfillment;
CREATE DATABASE IF NOT EXISTS tiki_live_scale;
CREATE DATABASE IF NOT EXISTS tiki_notification_campaign;
CREATE DATABASE IF NOT EXISTS tiki_loyalty;
CREATE DATABASE IF NOT EXISTS tiki_express;

-- Grant permissions to tiki user for all databases
GRANT ALL PRIVILEGES ON tiki_platform.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_auth.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_cart.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_checkout.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_inventory.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_order.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_payment.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_product.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_promotion.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_shipment.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_catalog.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_oms.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_logistics.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_notification.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_search.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_recommendation.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_analytics.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_fraud.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_billing.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_advertising.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_live_commerce.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_user_behavior.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_developer.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_sre.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_service_mesh.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_global_infra.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_rec_vector.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_payment_ledger.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_oms_fulfillment.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_live_scale.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_notification_campaign.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_loyalty.* TO 'tiki'@'%';
GRANT ALL PRIVILEGES ON tiki_express.* TO 'tiki'@'%';

FLUSH PRIVILEGES;
