apiVersion: v1
kind: ConfigMap
metadata:
  name: tiki-api-gateway-config
data:
  APP_NAME: "tiki-api-gateway"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  API_GATEWAY_HTTP_PORT: "8109"
  API_GATEWAY_GRPC_PORT: "9109"
  REDIS_ADDR: "redis-master.cache:6379"
  KAFKA_BROKERS: "kafka-headless.kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4318"
