apiVersion: v1
kind: Secret
metadata:
  name: tiki-api-gateway-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: "change-me-in-production"
  DB_HOST: "mysql-primary.database"
  DB_USER: "tiki"
  DB_PASSWORD: "change-me-in-production"
