apiVersion: v1
kind: Service
metadata:
  name: tiki-api-gateway
  labels:
    app: tiki-api-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8109
      targetPort: http
      protocol: TCP
      name: http
    - port: 9109
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: tiki-api-gateway
