apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tiki-canary-routing
  namespace: tiki
spec:
  hosts:
    - "api.tiki-clone.com"
  gateways:
    - tiki-gateway
  http:
    - match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: gateway-v2.tiki.svc.cluster.local
            port:
              number: 8080
          weight: 100
    - route:
        - destination:
            host: gateway.tiki.svc.cluster.local
            port:
              number: 8080
          weight: 90
        - destination:
            host: gateway-v2.tiki.svc.cluster.local
            port:
              number: 8080
          weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: auth-canary
  namespace: tiki
spec:
  hosts:
    - auth.tiki.svc.cluster.local
  http:
    - route:
        - destination:
            host: auth.tiki.svc.cluster.local
            port:
              number: 8080
          weight: 90
        - destination:
            host: auth-v2.tiki.svc.cluster.local
            port:
              number: 8080
          weight: 10
      timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: order-canary
  namespace: tiki
spec:
  hosts:
    - order.tiki.svc.cluster.local
  http:
    - match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: order-v2.tiki.svc.cluster.local
            port:
              number: 8080
          weight: 100
    - route:
        - destination:
            host: order.tiki.svc.cluster.local
            port:
              number: 8080
          weight: 95
        - destination:
            host: order-v2.tiki.svc.cluster.local
            port:
              number: 8080
          weight: 5
      timeout: 10s
