apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tiki-analytics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: tiki-analytics
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
