storage:
  wiredTiger:
    engineConfig:
      cacheSizeGB: 4

net:
  maxIncomingConnections: 20000

processManagement:
  fork: false

operationProfiling:
  slowOpThresholdMs: 100
  mode: off

systemLog:
  quiet: true