apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: tiki-gitops
  labels:
    app.kubernetes.io/name: argocd-cm
data:
  url: https://argocd.tiki-clone.com
  statusbadge.enabled: "true"
  repositories: |
    - url: https://github.com/tiki-clone/tiki-clone
      type: git
      name: tiki-clone
  resource.customizations: |
    networking.k8s.io/NetworkPolicy:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs
  accounts.admin: apiKey, login
  accounts.devops: login
  accounts.devops.enabled: "true"
  admin.enabled: "true"
  timeout.reconciliation: "180"
  timeout.hard.reconciliation: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: tiki-gitops
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:devops, applications, *, */*, allow
    p, role:devops, clusters, get, *, allow
    p, role:devops, repositories, *, *, allow
    p, role:devops, projects, *, *, allow
    g, devops, role:devops
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-ssh-known-hosts-cm
  namespace: tiki-gitops
